---
# Ansible Galaxy requirements
# External roles and collections needed for the project

# Collections
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.mysql
    version: ">=3.0.0"
  - name: community.docker
    version: ">=3.0.0"

# Roles from Ansible Galaxy
roles:
  # Security role
  - name: geerlingguy.security
    version: "2.0.1"
    
  # Firewall management
  - name: geerlingguy.firewall
    version: "2.8.0"
    
  # MySQL database
  - name: geerlingguy.mysql
    version: "4.3.4"
    
  # Docker support
  - name: geerlingguy.docker
    version: "7.0.2"
    
  # Monitoring
  - name: cloudalchemy.prometheus
    version: "2.17.0"
    
  # SSL certificates
  - name: geerlingguy.certbot
    version: "5.1.0"

# Git repositories
  - name: custom-common
    src: https://github.com/company/ansible-common.git
    version: main
    
  - name: custom-monitoring
    src: https://github.com/company/ansible-monitoring.git
    version: v1.2.0
    
  - name: custom-backup
    src: git+ssh://git@github.com/company/ansible-backup.git
    version: master